version: '3.8'

services:
  agentic-workflows:
    build: .
    container_name: agentic-workflows-app
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    labels:
      - "com.docker.compose.project=agentic-workflows"
      - "com.docker.compose.service=web"
    networks:
      - agentic-network
    
  # Optional: Add SSL termination with Let's Encrypt
  # nginx-proxy:
  #   image: nginxproxy/nginx-proxy:alpine
  #   container_name: nginx-proxy
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #     - ./certs:/etc/nginx/certs
  #     - ./vhost:/etc/nginx/vhost.d
  #     - ./html:/usr/share/nginx/html
  #   networks:
  #     - agentic-network

networks:
  agentic-network:
    driver: bridge
    
volumes:
  nginx_data:
    driver: local